---
services:
  radarr:
    image: braingremlin/docker-radarr:latest
    container_name: radarr
    env_file:
      - stack.env
    volumes:
      - ${CONFIG_DIR:-config}:/config
      - ${MEDIA_DIR:-media}:/media01
    security_opt:
      - no-new-privileges:true
    networks:
      media-bridge:
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  media-bridge:
    external: true
