---
services:
  sonarr:
    image: braingremlin/sonarr-py:latest
    container_name: sonarr
    environment:
      - PUID=1031
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume3/media02:/media02
    security_opt:
      - no-new-privileges:true
    ports:
      - 8989:8989
    restart: unless-stopped
