---
services:
  radarr:
    image: braingremlin/radarr-py:latest
    container_name: radarr
    env_file:
      - stack.env
    volumes:
      - ${CONFIG_DIR:-config}:/config
      - ${MEDIA_DIR:-media}:/media01
    security_opt:
      - no-new-privileges:true
    ports:
      - 7878:7878
    restart: unless-stopped
